# Generated by Django 3.1.5 on 2021-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('title', models.TextField()),
                ('content', models.TextField(default=None)),
            ],
        ),
    ]
