# Generated by Django 3.1.5 on 2021-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default=None, max_length=50)),
                ('platform', models.CharField(default=None, max_length=50)),
                ('descn', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='aim_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField(default='My aim is to be a successful Entrepreneur, by serving something to the society to meet its necessities and hence, upgrade its lifestyle.')),
                ('myself', models.TextField(default="Hello! I'm Arpit, a web developer(django framework), a tech enthusiast, and a guy slighty obsessed for code quality. I’m currently studying mechanical engineering in NIT patna. If you have a project that you want to get started or think you need my help with something, then get in touch.")),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('title', models.TextField()),
                ('content', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(default=None, max_length=150)),
                ('add_line2', models.CharField(default=None, max_length=150)),
                ('number', models.CharField(default=None, max_length=12)),
                ('email', models.EmailField(default='asme.arpitverma19@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('desc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40)),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default=None)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
