# Generated by Django 3.1.5 on 2021-01-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default=None, max_length=50)),
                ('platform', models.CharField(default=None, max_length=50)),
                ('descn', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('desc', models.TextField(default=None)),
            ],
        ),
    ]
