# Generated by Django 3.1.5 on 2021-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_achievement_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40)),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
    ]
