# Generated by Django 3.1.5 on 2021-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
