# Generated by Django 3.1.5 on 2021-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ip',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_ip',
            name='ip',
            field=models.GenericIPAddressField(default=None),
        ),
    ]
