# Generated by Django 3.1.5 on 2021-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20210126_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(default=None, max_length=150)),
                ('add_line2', models.CharField(default=None, max_length=150)),
                ('number', models.CharField(default=None, max_length=12)),
                ('email', models.EmailField(default='asme.arpitverma19@gmail.com', max_length=254)),
            ],
        ),
    ]
