# Generated by Django 3.1.5 on 2021-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='aim_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField(default='My aim is to be a successful Entrepreneur, by serving something to the society to meet its necessities and hence, upgrade its lifestyle.')),
                ('myself', models.TextField(default="Hello! I'm Arpit, a web developer(django framework), a tech enthusiast, and a guy slighty obsessed for code quality. I’m currently studying mechanical engineering in NIT patna. If you have a project that you want to get started or think you need my help with something, then get in touch.")),
            ],
        ),
    ]
